"""Cards table

Revision ID: 43df723a2166
Revises: 
Create Date: 2019-04-10 15:25:35.220384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43df723a2166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_visibility'), 'board', ['visibility'], unique=False)
    op.create_table('card',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('list_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('board_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list')
    op.drop_table('card')
    op.drop_index(op.f('ix_board_visibility'), table_name='board')
    op.drop_table('board')
    # ### end Alembic commands ###
