"""Cards table

Revision ID: 90e65fa269ec
Revises: 43df723a2166
Create Date: 2019-04-10 15:31:43.766399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e65fa269ec'
down_revision = '43df723a2166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_list_id_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'list', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_list_id_fkey', 'card', 'card', ['list_id'], ['id'])
    # ### end Alembic commands ###
